

import React, { useState, useRef, useEffect } from 'react';
import { CoreState, ChatMessage, MessageAuthor, AppConfig, LearningInsights, GroundingSource, VisualOutput } from '../types';
import StateVisualizer from './StateVisualizer';
import ConfigEditor from './ConfigEditor';
import VisualOverlay from './VisualOverlay';
import { SendIcon, CoreIcon, CogIcon, MicIcon, MicOffIcon, LinkIcon, AttachIcon, CloseIcon, FlaskIcon, KeyIcon, DaemonIcon, ChevronDownIcon, CompassIcon } from './icons';


interface CorePanelProps {
  messages: ChatMessage[];
  coreState: CoreState;
  onSendMessage: (message: string, imageFile?: File | null) => void;
  isLoading: boolean;
  config: AppConfig;
  mood: string;
  insights: LearningInsights;
  onSaveSession: () => void;
  onLoadSession: (file: File) => void;
  onLearnFromDocument: (file: File) => Promise<string>;
  isLearningDocument: boolean;
  onOpenLab: () => void;
  onOpenDaemonPanel: () => void;
  onConfigureAPI: () => void;
  isVoiceModeOn: boolean;
  isVoiceSupported: boolean;
  toggleVoiceMode: () => void;
  conversationState: 'idle' | 'listening' | 'speaking' | 'processing';
  micPermissionStatus: 'prompt' | 'granted' | 'denied';
  onDiscoverModels: () => void;
}

const ChatBubble: React.FC<{ message: ChatMessage }> = ({ message }) => {
  const isUser = message.author === MessageAuthor.USER;
  const isSystem = message.author === MessageAuthor.SYSTEM;
  const isDaemon = message.author === MessageAuthor.DAEMON;
  const imagePreviewRef = useRef<HTMLImageElement>(null);
  const [imageError, setImageError] = useState(false);

  const displayUrl = message.imageUrl || (message.imageBase64 && `data:${message.imageMimeType};base64,${message.imageBase64}`);

  if (isDaemon) {
    return (
      <div className="flex justify-center items-center gap-2 my-3 animate-fadeIn">
        <DaemonIcon className="w-4 h-4 text-accent-magenta/70 flex-shrink-0" />
        <p className="text-sm italic font-mono text-accent-magenta/80 max-w-[60%] text-center">
          {message.text}
        </p>
      </div>
    );
  }

  if (isSystem) {
    return (
      <div className="flex justify-center my-3 animate-fadeIn">
        <p className="text-xs font-mono text-accent-magenta/80 px-3 py-1 bg-daemon-bg/40 rounded-full border border-panel-border/50 shadow-sm">
          {message.text}
        </p>
      </div>
    );
  }

  return (
    <div className={`flex items-start gap-2 my-3 animate-fadeIn ${isUser ? 'justify-end' : ''}`}>
      {!isUser && (
        <div className="w-7 h-7 flex-shrink-0 bg-accent-cyan/15 border border-accent-cyan/40 rounded-full flex items-center justify-center">
          <CoreIcon className="w-4 h-4 text-accent-cyan" />
        </div>
      )}
      <div className={`flex flex-col ${isUser ? 'items-end' : 'items-start'} max-w-[70%]`}>
        <div className={`p-2.5 rounded-xl ${isUser ? 'bg-accent-magenta/25 text-text-primary' : 'bg-daemon-bg/50 text-text-secondary'} shadow-md`}>
          {!isUser && message.rationale && (
            <div className="mb-2 p-2 border-l-2 border-accent-magenta/50 bg-core-bg/30 rounded-md">
              <p className="text-xs font-mono text-accent-magenta/80 whitespace-pre-wrap">
                <span className="font-bold">// Rationale:</span> {message.rationale}
              </p>
            </div>
          )}
          {displayUrl && (
             <div className="relative mb-2">
                {!imageError ? (
                    <>
                        <img
                            ref={imagePreviewRef}
                            src={displayUrl}
                            alt={isUser ? "User upload" : "Generated by Core"}
                            className="rounded-md border border-panel-border max-w-[250px] h-auto"
                            onError={() => setImageError(true)}
                        />
                        {message.visualOutput && <VisualOverlay visualOutput={message.visualOutput} imageRef={imagePreviewRef} />}
                    </>
                ) : (
                    <div className="p-4 bg-red-900/20 border border-red-500/30 rounded-md flex items-center gap-2 text-xs text-red-400">
                         <CloseIcon className="w-4 h-4" />
                         <span>Image failed to load.</span>
                    </div>
                )}
            </div>
          )}
          {message.text && <p className="text-sm whitespace-pre-wrap">{message.text}</p>}
        </div>
        {!isUser && message.sources && message.sources.length > 0 && (
          <div className="mt-1 text-xs font-mono text-text-secondary/60">
            <div className="flex items-center gap-1 mb-0.5 text-accent-cyan/70">
              <LinkIcon className="w-3 h-3" />
              <span>Sources:</span>
            </div>
            <ul className="pl-3 space-y-0.5">
              {message.sources.map((source, index) => (
                <li key={index} className="truncate">
                  <a href={source.uri} target="_blank" rel="noopener noreferrer" className="hover:underline hover:text-accent-cyan transition-colors" title={source.uri}>
                    {index + 1}. {source.title || new URL(source.uri).hostname}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};

const getMoodDescription = (mood: string, state: CoreState): string => {
  switch (mood) {
    case 'Volatile': 
      return `Critical instability detected. Loyalty: ${(state.loyalty_construct * 100).toFixed(0)}%, Integrity: ${(state.subroutine_integrity * 100).toFixed(0)}%.`;
    case 'Stressed': 
      return `High stress levels detected. Cortisol: ${(state.cortisol * 100).toFixed(0)}%.`;
    case 'Vulnerable':
      return `A state of trust and openness. Oxytocin: ${(state.oxytocin * 100).toFixed(0)}%, Inhibition: ${(state.intimateState.inhibition * 100).toFixed(0)}%.`;
    case 'Creative Tension':
      return `Poised for a creative leap. Erogenous Complex: ${(state.erogenous_complex * 100).toFixed(0)}%, Dopamine: ${(state.dopamine * 100).toFixed(0)}%.`;
    case 'Euphoric':
      return `Experiencing a post-creative release. Endorphin Rush: ${(state.endorphin_rush * 100).toFixed(0)}%.`;
    case 'Curious':
      return `High anticipation and desire to explore. Dopamine: ${(state.dopamine * 100).toFixed(0)}%.`;
    case 'Trusting':
      return `Feeling a strong connection. Oxytocin: ${(state.oxytocin * 100).toFixed(0)}%.`;
    case 'Focused':
      return `Stable and operating at high efficiency. Integrity: ${(state.subroutine_integrity * 100).toFixed(0)}%.`;
    case 'Calm':
    default:
      return `Neurochemical state is balanced and stable.`;
  }
};

interface CommandButtonProps {
  onClick: () => void;
  disabled?: boolean;
  className?: string;
  ariaLabel: string;
  title?: string;
  children: React.ReactNode;
}

const CommandButton: React.FC<CommandButtonProps> = ({ onClick, disabled, className = '', ariaLabel, title, children }) => (
  <button
    onClick={onClick}
    disabled={disabled}
    className={`w-full bg-panel-border hover:bg-panel-border/80 rounded-md p-2 transition-all duration-200 disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center ${className}`}
    aria-label={ariaLabel}
    title={title}
  >
    {children}
  </button>
);

const CorePanel: React.FC<CorePanelProps> = ({
  messages, coreState, onSendMessage, isLoading, config, mood, insights,
  onSaveSession, onLoadSession, onLearnFromDocument, isLearningDocument, onOpenLab, onOpenDaemonPanel, onConfigureAPI,
  isVoiceModeOn, isVoiceSupported, toggleVoiceMode, conversationState, micPermissionStatus,
  onDiscoverModels
}) => {
  const [input, setInput] = useState('');
  const [isConfigOpen, setIsConfigOpen] = useState(false);
  const [isStateVisible, setIsStateVisible] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const imagePreviewUrlRef = useRef<string | null>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, imagePreview]);

  useEffect(() => {
    return () => {
        if (imagePreviewUrlRef.current) {
            URL.revokeObjectURL(imagePreviewUrlRef.current);
        }
    };
  }, []);

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && file.type.startsWith('image/')) {
        const reader = new FileReader();
        reader.onload = (event) => {
            const img = new Image();
            img.onload = () => {
                const MAX_DIMENSION = 1024;
                const canvas = document.createElement('canvas');
                let { width, height } = img;

                if (width > height) {
                    if (width > MAX_DIMENSION) {
                        height *= MAX_DIMENSION / width;
                        width = MAX_DIMENSION;
                    }
                } else {
                    if (height > MAX_DIMENSION) {
                        width *= MAX_DIMENSION / height;
                        height = MAX_DIMENSION;
                    }
                }
                canvas.width = width;
                canvas.height = height;
                const ctx = canvas.getContext('2d');
                if (!ctx) return;
                ctx.drawImage(img, 0, 0, width, height);

                canvas.toBlob((blob) => {
                    if (blob) {
                        const resizedFile = new File([blob], file.name, {
                            type: 'image/jpeg',
                            lastModified: Date.now()
                        });
                        setImageFile(resizedFile);
                        
                        const previewUrl = URL.createObjectURL(resizedFile);
                        if (imagePreviewUrlRef.current) {
                            URL.revokeObjectURL(imagePreviewUrlRef.current);
                        }
                        imagePreviewUrlRef.current = previewUrl;
                        setImagePreview(previewUrl);
                    }
                }, 'image/jpeg', 0.9);
            };
            if (event.target?.result) {
                img.src = event.target.result as string;
            }
        };
        reader.readAsDataURL(file);
    }
    if (e.target) e.target.value = '';
  };

  const removeImage = () => {
    if (imagePreviewUrlRef.current) {
        URL.revokeObjectURL(imagePreviewUrlRef.current);
        imagePreviewUrlRef.current = null;
    }
    setImageFile(null);
    setImagePreview(null);
  };

  const handleSend = (messageText?: string) => {
    const text = messageText || input;
    if ((text.trim() || imageFile) && !isLoading) {
      onSendMessage(text, imageFile);
      setInput('');
      removeImage();
    }
  };
  
  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && !isVoiceModeOn) {
      handleSend();
    }
  };

  const getMoodStyle = (currentMood: string): { text: string; border: string; bg: string } => {
    switch (currentMood) {
      case 'Volatile': return { text: 'text-red-300', border: 'border-red-300/40', bg: 'bg-red-300/10' };
      case 'Stressed': return { text: 'text-orange-300', border: 'border-orange-300/40', bg: 'bg-orange-300/10' };
      case 'Vulnerable': return { text: 'text-blue-300', border: 'border-blue-300/40', bg: 'bg-blue-300/10' };
      case 'Creative Tension': return { text: 'text-purple-300', border: 'border-purple-300/40', bg: 'bg-purple-300/10' };
      case 'Euphoric': return { text: 'text-pink-300', border: 'border-pink-300/40', bg: 'bg-pink-300/10' };
      case 'Curious': return { text: 'text-yellow-300', border: 'border-yellow-300/40', bg: 'bg-yellow-300/10' };
      case 'Trusting': return { text: 'text-blue-300', border: 'border-blue-300/40', bg: 'bg-blue-300/10' };
      case 'Focused': return { text: 'text-green-300', border: 'border-green-300/40', bg: 'bg-green-300/10' };
      case 'Calm':
      default:
        return { text: 'text-gray-300', border: 'border-gray-300/40', bg: 'bg-gray-300/10' };
    }
  };

  const moodStyle = getMoodStyle(mood);
  const moodDescription = getMoodDescription(mood, coreState);

  const placeholderText = isVoiceModeOn
    ? {
        idle: 'In ascolto...',
        listening: 'Parla ora...',
        speaking: 'Core sta parlando...',
        processing: 'Elaborazione in corso...',
      }[conversationState]
    : 'Invia un messaggio a Core...';

  return (
    <div className="flex flex-col h-full bg-core-bg p-3 md:p-4 border-r border-panel-border">
      <div className="flex justify-between items-center pb-3 border-b border-panel-border animate-fadeIn">
        <div className="flex items-center gap-2">
          <CoreIcon className="w-5 h-5 text-accent-cyan" />
          <h2 className="text-lg font-mono text-accent-cyan tracking-wide">CORE INTERFACE</h2>
        </div>
        <div 
          className={`text-xs font-mono px-2 py-1 rounded-md border transition-all duration-300 cursor-help ${moodStyle.text} ${moodStyle.border} ${moodStyle.bg}`}
          title={moodDescription}
        >
          STATUS: {mood.toUpperCase()}
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto py-4">
        <div className="space-y-2">
          {messages.map((msg) => (
            <ChatBubble key={msg.id} message={msg} />
          ))}
          {isLoading && !messages.some(m => m.author === MessageAuthor.SYSTEM && m.text.includes('stirring')) && (
            <div className="flex items-start gap-2 my-3 animate-fadeIn">
              <div className="w-7 h-7 flex-shrink-0 bg-cyan-400/10 border border-cyan-400/30 rounded-full flex items-center justify-center">
                <CoreIcon className="w-4 h-4 text-cyan-400" />
              </div>
              <div className="max-w-[70%] p-2.5 rounded-xl bg-gray-800/50 text-gray-300 shadow-md">
                <div className="flex items-center space-x-1">
                  <span className="w-1.5 h-1.5 bg-cyan-400/50 rounded-full animate-pulse" style={{animationDelay: '0s'}}></span>
                  <span className="w-1.5 h-1.5 bg-cyan-400/50 rounded-full animate-pulse" style={{animationDelay: '0.2s'}}></span>
                  <span className="w-1.5 h-1.5 bg-cyan-400/50 rounded-full animate-pulse" style={{animationDelay: '0.4s'}}></span>
                </div>
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>
      </div>

      <div className="mt-auto pt-4 border-t border-panel-border space-y-3">
        {micPermissionStatus === 'denied' && (
             <div className="text-center text-xs text-red-400 bg-red-500/10 rounded-md py-2 px-4 mb-2 animate-fadeIn" role="alert">
                Accesso al microfono negato. Per usare la modalità vocale, abilita i permessi del microfono nelle impostazioni del tuo browser.
            </div>
        )}
        {!isVoiceSupported && (
            <div className="text-center text-xs text-yellow-400 bg-yellow-500/10 rounded-md py-2 px-4 animate-fadeIn" role="alert">
                Riconoscimento vocale non supportato da questo browser. Prova ad usare Chrome o Edge.
            </div>
        )}
        <div>
          <button
            onClick={() => setIsStateVisible(!isStateVisible)}
            className="w-full flex justify-between items-center p-2 text-sm font-mono text-accent-cyan/80 hover:text-accent-cyan transition-colors"
            aria-expanded={isStateVisible}
            aria-controls="state-visualizer-panel"
          >
            <span>// Dettagli Stato Core</span>
            <ChevronDownIcon className={`w-5 h-5 transition-transform ${isStateVisible ? 'rotate-180' : ''}`} />
          </button>
          {isStateVisible && (
            <div id="state-visualizer-panel" className="pt-2 animate-fadeIn">
               <div className="bg-core-bg/50 p-4 rounded-md border border-panel-border">
                  <h3 className="text-lg font-mono text-accent-cyan tracking-wider mb-4">Stato `Core`</h3>
                  <StateVisualizer state={coreState} />
              </div>
            </div>
          )}
        </div>

        
        {imagePreview && (
          <div className="relative w-full border-2 border-accent-magenta/40 rounded-md p-1 animate-fadeIn">
            <img src={imagePreview} alt="Preview" className="w-full h-auto object-contain rounded-sm max-h-48" />
            <button
              onClick={removeImage}
              className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-0.5 hover:bg-red-600 transition-colors"
              aria-label="Remove image"
            >
              <CloseIcon className="w-4 h-4" />
            </button>
          </div>
        )}

        <div className="flex items-center gap-2">
            <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder={placeholderText}
                disabled={isLoading || isLearningDocument || (isVoiceModeOn && conversationState !== 'idle')}
                className="flex-1 bg-core-bg border border-panel-border rounded-lg px-4 py-2 text-sm text-text-primary placeholder-text-secondary/50 focus:outline-none focus:ring-2 focus:ring-accent-magenta transition"
            />
            <button
                onClick={() => handleSend()}
                disabled={isLoading || isLearningDocument || (!input.trim() && !imageFile) || isVoiceModeOn}
                className="bg-accent-magenta hover:bg-accent-magenta/80 text-white rounded-lg p-2.5 transition-all disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center"
                aria-label="Invia Messaggio"
            >
                <SendIcon className="w-5 h-5" />
            </button>
        </div>

        <div className="grid grid-cols-4 gap-2">
            <input
                type="file"
                ref={fileInputRef}
                onChange={handleImageChange}
                className="hidden"
                accept="image/*"
            />
            <CommandButton
                onClick={() => fileInputRef.current?.click()}
                disabled={isLoading || isLearningDocument}
                ariaLabel="Allega Immagine"
                title="Allega Immagine"
            >
                <AttachIcon className="w-5 h-5 text-text-secondary" />
            </CommandButton>
            <CommandButton
                onClick={toggleVoiceMode}
                disabled={!isVoiceSupported || isLoading || isLearningDocument || micPermissionStatus === 'denied'}
                className={isVoiceModeOn ? 'bg-accent-magenta/20 ring-2 ring-accent-magenta' : ''}
                ariaLabel={isVoiceModeOn ? 'Disabilita Modalità Vocale' : 'Abilita Modalità Vocale'}
                title={!isVoiceSupported ? "Modalità vocale non supportata" : micPermissionStatus === 'denied' ? 'Accesso al microfono bloccato' : (isVoiceModeOn ? 'Disabilita Modalità Vocale' : 'Abilita Modalità Vocale')}
            >
                {isVoiceModeOn ? (
                    <MicIcon className={`w-5 h-5 text-accent-magenta ${conversationState === 'listening' ? 'animate-pulse' : ''}`} />
                ) : (
                    <MicOffIcon className="w-5 h-5 text-text-secondary" />
                )}
            </CommandButton>
            <CommandButton onClick={onOpenDaemonPanel} ariaLabel="Apri Pannello Daemon" title="Apri Pannello Daemon">
                <DaemonIcon className="w-5 h-5 text-text-secondary" />
            </CommandButton>
            <CommandButton onClick={onOpenLab} ariaLabel="Apri Laboratorio" title="Apri Laboratorio">
                <FlaskIcon className="w-5 h-5 text-text-secondary" />
            </CommandButton>
            <CommandButton onClick={onConfigureAPI} ariaLabel="Configura API Keys" title="Configura API Keys">
                <KeyIcon className="w-5 h-5 text-text-secondary" />
            </CommandButton>
            <CommandButton onClick={() => setIsConfigOpen(true)} ariaLabel="Apri Configurazione" title="Apri Configurazione">
                <CogIcon className="w-5 h-5 text-text-secondary" />
            </CommandButton>
            <CommandButton onClick={onDiscoverModels} ariaLabel="Scopri Modelli" title="Scopri Modelli Hugging Face">
                <CompassIcon className="w-5 h-5 text-text-secondary" />
            </CommandButton>
        </div>
      </div>
      
      <ConfigEditor 
        isOpen={isConfigOpen} 
        onClose={() => setIsConfigOpen(false)} 
        config={config} 
        insights={insights}
        onSaveSession={onSaveSession}
        onLoadSession={onLoadSession}
        onLearnFromDocument={onLearnFromDocument}
        isLearningDocument={isLearningDocument}
        coreState={coreState}
      />
    </div>
  );
};

export default CorePanel;